apiVersion: v1
kind: Pod
metadata:
  name: backend-worker
  labels:
   app: redis
   environment: production
   team: sre-backend

spec:
  containers:
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379