apiVersion: v1
kind: Pod
metadata:
  name: qos-demo

spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m" # 100 millicores (0.1 CPU)
      limits:
        memory: "256Mi"
        cpu: "250m"