apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc
spec:
  storageClassName: standard # Use the default class name from Task 5
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
