apiVersion: v1
kind: Service
metadata:
  name: app-clusterip
  namespace: dev

spec:
  type: ClusterIP
  selector:
    app: nginx # This MUST match the labels in your Deployment
  ports:
  - protocol: TCP
    port: 80          # The port the Service listens on
    targetPort: 80    # The port the Container is listening on
